### ISSUE TITLE
Feature: User can login 

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/protrak2#1]
## ⚙️ Feature

User can login

## 📐 Functionality

User will see a login button which reveals a form to enter username and login 

## 🖼️ Wireframes

![Screen Shot 2023-02-21 at 16 16 16 PM](https://user-images.githubusercontent.com/98434681/220488108-83afe376-fb56-4ddd-8f4b-258789e3e415.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create table for users
- [x] Update `data.sql` to load dummy data for testing

### ☁️ Server Tasks

- [x] Update `server/index.js` to have an authentication endpoint for users using argon2
- [x] have endpoint create a user token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the nav bar
- [x] create a component for auth page
- [x] update the nav bar to show correct links based on login auth

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
